{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ai-sre-copilot.namespace" . }}
  labels:
    {{- include "ai-sre-copilot.labels" . | nindent 4 }}
{{- end }}
